### ISSUE TITLE
Auto Compressor Doesn't Work

### ISSUE THREAD

**Issue by cwilkinsvi** [Discomanco/Enigmatica2ExpertSkyblock#125] opened 2018-09-17 22:26 UTC
#### Issue Description
All Ex nihilo ore pieces can not be crafted in the ex compressum auto compressor. Changed since last version. Only recipes for ore pieces are now crafting tables.
#### Modpack version (Do not use "latest")
1.5
#### Crash Report
N/A
[pastebin/gist/etc link here]

**Comment by NillerMedDild** [comment] 2018-09-18 09:48
So the issue isn't that recipes for Ore Pieces -> Ore are gone, but that the Auto Compressor can no longer compress them, right?

**Comment by cwilkinsvi** [comment] 2018-09-18 12:59
Correct. Further testing last night showed the auto compressor had no uses.

**Comment by NillerMedDild** [comment] 2018-09-18 14:30
Very misleading title :P

**Comment by cwilkinsvi** [comment] 2018-09-18 14:47
It was somehow still compressing redstone yesterday when I first loaded up the pack, so I thought it was an issue with Ex Nihilo. My apologies.

**Comment by NillerMedDild** [comment] 2018-09-18 16:35
No worries :)

**Comment by NillerMedDild** [comment] 2018-09-18 16:37
I'm fairly certain the issue is that resources obtained through Sieves have empty NBT data.

**Comment by NillerMedDild** [comment] 2018-09-19 16:43
Fixed in https://github.com/BloodWorkXGaming/ExNihiloCreatio/issues/115#issuecomment-422751064

**Closed by NillerMedDild** 2018-09-19 16:43 UTC
Labels: fixed in dev, mod issue
