### ISSUE TITLE
Ex nihilo creatio/sieve issues

### ISSUE THREAD

**Issue by Myth32733** [Discomanco/Enigmatica2ExpertSkyblock#129] opened 2018-09-18 23:33 UTC
sieves are creating items with empty NBT tags thus creating a horrible issue where I can have two of the exact same item they just don't stack because of the empty NBT tag.

 V1.5 (Do not use "latest")

 N/A

**Comment by NillerMedDild** [comment] 2018-09-19 06:43
Duplicate of #125

**Closed by NillerMedDild** 2018-09-19 06:43 UTC
